title: "Saul's Blog"
description: "Just do it!"
tagline: "萍水相逢，尽是他乡之客"
url: "https://xingfenyizhen.github.io"
baseurl: ""
lang: "zh-CN"
timezone: "Asia/Shanghai"
header_image: "/assets/img/1.jpg"
github_username: "xingfenyizhen"

author:
  name: "Zhengyu Wang"
  email: "18986377619@163.com"

permalink: /posts/:title/
future: false
excerpt_separator: "<!--more-->"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: feed.xml

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
